---
title: "FAO_trade"
author: "Caitie"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) #new format for R to neaten data ("pipe" = %>%)
library(ggplot2) #plotting
library(data.table) #fread function -> reading function for large datasets
library(countrycode) #ISO3 country codes
library(here) #best practice for setting working directory to GitHub

```

```{r}
trade_partners<-read_csv(here("raw_data/FAO_trade/FI_Trade_Partners_2023.1.0/TRADE_PARTNERS_QUANTITY.csv"))
```

# Get commodities for the top traded species

Atlantic herring


```{r}
commodities<-read_csv(here("raw_data/FAO_trade/FI_Trade_Partners_2023.1.0/CL_FI_COMMODITY_ISSCFC.csv"))

ah<-commodities %>% 
  filter(str_detect(Name_En, "Atlantic herring")) %>% 
  mutate(Species = "Atlantic herring")

#ac<-commodities %>% 
#  filter(str_detect(Name_En, "Atlantic cod"))  %>% 
 # mutate(Species = "Atlantic cod")

#st<-commodities %>% 
 # filter(str_detect(Name_En, "Skipjack tuna"))  %>% 
 # mutate(Species = "Skipjack tuna")

#am<-commodities %>% 
 # filter(str_detect(Name_En, "Atlantic mackerel"))  %>% 
 # mutate(Species = "Atlantic mackerel")

#target_commodities<-rbind(ah, ac, st, am)
target_commodities<-ah
```

```{r}
target_trade<-trade_partners %>% 
  filter(COMMODITY.FAO_CODE %in% target_commodities$Code)

target_trade<-left_join(target_trade, target_commodities, by = c("COMMODITY.FAO_CODE" = "Code"))
```


```{r}
countries<-read_csv(here("raw_data/FAO_trade/FI_Trade_Partners_2023.1.0/CL_FI_COUNTRY_GROUPS.csv")) %>% 
  select(UN_Code, ISO3_Code, Name_En)
```

# List of countries that import and export to eachother

```{r}
trade_data2<-target_trade %>% 
  group_by(PERIOD, COUNTRY_REPORTER.UN_CODE, COUNTRY_PARTNER.UN_CODE,Species) %>% 
  summarise(Tonnage = sum(VALUE, na.rm = TRUE)) %>% 
  ungroup() 

sub_trade_data<-trade_data2 %>% 
  select(COUNTRY_REPORTER.UN_CODE, COUNTRY_PARTNER.UN_CODE)      #create data set with only Export and Import Combinations

sub_trade_data2<-unique(sub_trade_data[c("COUNTRY_REPORTER.UN_CODE", "COUNTRY_PARTNER.UN_CODE")])  #omit the duplicated Export Import combinations

countrytrade1<-merge(sub_trade_data2,setNames(sub_trade_data2,rev(names(sub_trade_data2)))) #create data frame of countries that both import & export to each other 

length(unique(countrytrade1$COUNTRY_REPORTER.UN_CODE)) #154 countries - visually check some in sub_trade_data2 to make sure it makes sense
length(unique(countrytrade1$COUNTRY_PARTNER.UN_CODE)) 
```

```{r}

CT<-c(2019,2020,2021) #years 



#find every trade combination:
d1<-as.data.frame(t(apply(countrytrade1,1,sort)))
countrytrade<-countrytrade1[!duplicated(d1),]          #remove the duplicated combinations (i.e. AUS:CHN and CHN:AUS)

test_ex<-unique(countrytrade$COUNTRY_REPORTER.UN_CODE)
test_im<-(unique(countrytrade$COUNTRY_PARTNER.UN_CODE))
both<-length(unique(c(test_ex,test_im)))

#create empty sheets/function/cell for for loop
all<-c()
final_all_years<-c()

for(c in 1:nrow(countrytrade)){
#for(c in 230:250){ #this is just for debugging/problem solving
  print(c)
    
  
  #Calculate values for ALL data (not just to species level)
  
  # Totaltradedx <- target_trade %>% ##for calculating total tonnage traded
     #   filter(COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c]) 
      
    #  Totaltradedy <- target_trade %>% ##for calculating total tonnage traded 
    #    filter(COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c]) 
      
  
  #filter the cleaned trade data for the observations for the selected country combination c (i.e. where AUS:CHN = sub1 and CHN:AUS = sub2)
  sub1<-target_trade %>% ##for calculating total tonnage traded
        filter(COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c])  #export country = country_x
             
  sub2<-target_trade %>% ##for calculating total tonnage traded 
        filter(COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c])  #export country = country_y
  
  sub1_total_trade<-sum(sub1$VALUE, na.rm = T)
  sub2_total_trade<-sum(sub2$VALUE, na.rm = T)
  
  n_species_all<-unique(c(unique(sub1$COMMODITY.FAO_CODE),unique(sub2$COMMODITY.FAO_CODE)))

  
  #skip remainder of the loop if there is no reciprocal trading between countries
  if(nrow(sub1)>0 & nrow(sub2)>0){

  sub1_total_sp<-unique(sub1$COMMODITY.FAO_CODE)
  sub2_total_sp<-unique(sub2$COMMODITY.FAO_CODE)
  
    c1<-unique(sub1$COUNTRY_REPORTER.UN_CODE) #ISO3 country code for country x for naming the final write.csv file
    c2<-unique(sub2$COUNTRY_REPORTER.UN_CODE) #ISO3 country code for country y for naming the final write.csv file
    
    c1_name<-countries %>% 
      filter(UN_Code == sub1$COUNTRY_REPORTER.UN_CODE)
    
    c2_name<-countries %>% 
      filter(UN_Code == sub2$COUNTRY_REPORTER.UN_CODE)
  
  total_sp<-unique(c(unique(sub1$COMMODITY.FAO_CODE), unique(sub2$COMMODITY.FAO_CODE)))
  
    #filter country 1(x) export species to match country 2(y) export species, and country 2(y) exports data to match country 2(y) exports species 
    like_sub1<-sub1 %>% 
      filter(COMMODITY.FAO_CODE %in% sub2_total_sp)
   
     like_sub2<-sub2 %>% 
      filter(COMMODITY.FAO_CODE %in% sub1_total_sp)
     
     if(nrow(like_sub1)>0 & nrow(like_sub2)>0){
    
    #check 'unique' should have the same number of species - can also check like_sub1 and like_sub2 for same species names above.
    sub1_total_sp_like1<-length(unique(like_sub1$COMMODITY.FAO_CODE))
    sub2_total_sp_like2<-length(unique(like_sub2$COMMODITY.FAO_CODE))
    
    total_like_sp<-unique(c(sub1_total_sp_like1,sub2_total_sp_like2))
    
    join<-rbind(like_sub1, like_sub2)
    
     total_spp_tonnes<- join%>% 
      group_by(COUNTRY_REPORTER.UN_CODE, COMMODITY.FAO_CODE, Name_En) %>% 
      summarise(total_like_tonnes = sum(VALUE, na.rm = T))

    min_value<-total_spp_tonnes%>% 
      group_by(COMMODITY.FAO_CODE) %>% 
      summarise(min_tonnes = min(total_like_tonnes, na.rm = T)) %>% 
      ungroup() %>% 
      mutate(redun_tonnes = min_tonnes*2)
         
    df_all_years<-data.frame(x = c1, 
                             y = c2,
                             Export_ISO3 = c1_name$ISO3_Code,
                             Import_ISO3 = c2_name$ISO3_Code,
                            # total_traded_x = sum(Totaltradedx$Tonnage, na.rm = T),
                            # total_traded_y = sum(Totaltradedy$Tonnage, na.rm = T),
                             total_traded_spp_x = sum(sub1$VALUE, na.rm = T),
                             total_traded_spp_y = sum(sub2$VALUE, na.rm = T),
                             total_traded_like_spp = sum(total_spp_tonnes$total_like_tonnes, na.rm = T),
                             total_traded_redun_spp = sum(min_value$redun_tonnes,na.rm = T),
                             n_species = length(n_species_all),
                             n_species_spp = length(total_sp),
                             n_species_spp_like = length(total_like_sp))
    
   # df_all_years<-df_all_years %>% 
    #              mutate(total_country_trade = total_traded_x + total_traded_y,
     #                        prop_redun_like_trade = total_traded_redun_spp/total_country_trade,
     #                        prop_redun_like_trade_spp = total_traded_redun_spp/total_traded_like_spp)
    
    final_all_years<-rbind(final_all_years, df_all_years)
    
    final_join_year2<-c()
    #skip the remainder of the loop if the countries do not trade at least 1 of the same species (i.e. if no two-way trade occurs)
    #create for loop to analyse species traded in each year
    for(i in 1:length(CT)){
      ##The next few lines are for calculating the total tonnage of seafood exported to and from one country to the other country for year i below (i.e. before omitting data)
      Totaltradedx_year <- target_trade %>% ##for calculating total tonnage traded for year i below
        filter(PERIOD == CT[i],
               COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c]) 
      
      Totaltradedy_year <- target_trade %>% ##for calculating total tonnage traded for year i below
        filter(PERIOD == CT[i],
               COUNTRY_REPORTER.UN_CODE == countrytrade$COUNTRY_PARTNER.UN_CODE[c] & COUNTRY_PARTNER.UN_CODE == countrytrade$COUNTRY_REPORTER.UN_CODE[c]) 
      
      n_species_all_year<-unique(c(unique(Totaltradedx_year$COMMODITY.FAO_CODE),unique(Totaltradedy_year$COMMODITY.FAO_CODE)))

      #filter for same species (i.e. identify the like-for-like [or two-way traded] species in year i)
      sub1_year<-sub1 %>% 
        filter(PERIOD == CT[i]) %>% 
        mutate(total_tonnes_spp_year = sum(VALUE, na.rm = T))
      
      sub2_year<-sub2 %>% 
        filter(PERIOD == CT[i]) %>% 
        mutate(total_tonnes_spp_year = sum(VALUE, na.rm = T))
      
      n_species_spp_year<-unique(c(unique(sub1_year$COMMODITY.FAO_CODE), unique(sub2_year$COMMODITY.FAO_CODE)))
      
       
       #skip remainder of the loop if countries did not trade the same species in year i (i.e. move on to year i + 1)
       if(nrow(sub1_year)>0 & nrow(sub2_year)>0){
  
      like_sub1_year<-sub1 %>% 
        filter(PERIOD == CT[i],
          COMMODITY.FAO_CODE %in% sub2_year$COMMODITY.FAO_CODE)
      
      like_sub2_year<-sub2 %>% 
        filter(PERIOD == CT[i],
          COMMODITY.FAO_CODE %in% sub1_year$COMMODITY.FAO_CODE)
      
      n_species_spp_like_year<-unique(c(unique(like_sub1_year$COMMODITY.FAO_CODE), unique(like_sub2_year$COMMODITY.FAO_CODE)))
      
      if(length(n_species_spp_like_year)>0){
  
    join_year<-rbind(like_sub1_year, like_sub2_year)
    
     total_spp_tonnes_year<- join_year %>% 
      group_by(COUNTRY_REPORTER.UN_CODE, COMMODITY.FAO_CODE, Name_En) %>% 
      summarise(total_like_tonnes_year = sum(VALUE, na.rm = T))

    min_value_year<-total_spp_tonnes_year%>% 
      group_by(COMMODITY.FAO_CODE) %>% 
      summarise(min_tonnes_year = min(total_like_tonnes_year, na.rm = T)) %>% 
      ungroup() %>% 
      mutate(redun_tonnes_year = min_tonnes_year*2)
      
          df_year<-data.frame(x = c1, 
                             y = c2,
                             Export_iso3 =c1_name$ISO3_Code,
                             Import_iso3 = c2_name$ISO3_Code,
                             Year = CT[i],
                             total_traded_x_year = sum(Totaltradedx_year$VALUE, na.rm = T),
                             total_traded_y_year = sum(Totaltradedy_year$VALUE, na.rm = T),
                             total_traded_spp_x_year = sum(sub1_year$VALUE, na.rm = T),
                             total_traded_spp_y_year = sum(sub2_year$VALUE, na.rm = T),
                             total_traded_like_spp_year = sum(total_spp_tonnes_year$total_like_tonnes_year, na.rm = T),
                             total_traded_redun_spp_year = sum(min_value_year$redun_tonnes_year,na.rm = T),
                             n_species_year = length(n_species_all_year),
                             n_species_spp_year = length(n_species_spp_year),
                             n_species_spp_like_year = length(n_species_spp_like_year))
          
          df_year<-df_year %>% 
                  mutate(total_country_trade_year = total_traded_x_year + total_traded_y_year,
                             prop_redun_like_trade_year = total_traded_redun_spp_year/total_country_trade_year,
                             prop_redun_like_trade_spp_year = total_traded_redun_spp_year/total_traded_like_spp_year)
          
          final_join_year<-join_year %>% 
            mutate(total_traded_x_year = sum(Totaltradedx_year$VALUE, na.rm = T),
                             total_traded_y_year = sum(Totaltradedy_year$VALUE, na.rm = T),
                             total_traded_spp_x_year = sum(sub1_year$VALUE, na.rm = T),
                             total_traded_spp_y_year = sum(sub2_year$VALUE, na.rm = T),
                             total_traded_like_spp_year = sum(total_spp_tonnes_year$total_like_tonnes_year, na.rm = T),
                             total_traded_redun_spp_year = sum(min_value_year$redun_tonnes_year,na.rm = T),
                             n_species_year = length(n_species_all_year),
                             n_species_spp_year = length(n_species_spp_year),
                             n_species_spp_like_year = length(n_species_spp_like_year),
                   total_country_trade_year = total_traded_x_year + total_traded_y_year,
                             prop_redun_like_trade_year = total_traded_redun_spp_year/total_country_trade_year,
                             prop_redun_like_trade_spp_year = total_traded_redun_spp_year/total_traded_like_spp_year)
          
         final_join_year2<-rbind(final_join_year2, final_join_year)
          
          
       #   final_df<-rbind(final_df, df_year) #combine sum data into one data file for every year
      
              all<-rbind(all, df_year)
       }
    }
#write.csv(final_df, paste0(here("output_data/Country_Country/"),c1,"_",c2,"_like_species_by_year_july2022.csv"))
      
    }
    
     write.csv(final_join_year2, here(paste0("output_data/FAO/",c1_name$ISO3_Code,"_", c2_name$ISO3_Code, "_like_species_trade.csv")))
    }
  }

    }
  write.csv(all, here("output_data/FAO/like_traded_year_calculations.csv"))
  
  write.csv(final_all_years,here("output_data/FAO/Like_species_all_years.csv"))
```

# Compare with Watson results?

```{r}
ah_fao<-read_csv(here("output_data/FAO/Like_species_all_years.csv"))
```


```{r}
sp<-read_csv(here("output_data/Redundant_trade_by_species_2013_2015.csv"))

test<-read_csv(here("output_data/Country_redundant_species_results.csv")) %>% 
  filter(CommonName == "Atlantic herring",
         Year %in% c(2013,2014,2015))
```

